import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

/**
 * Metrics summary for a single API.
 */
export interface ApiMetrics {
  apiId: string;
  apiName: string;
  callCount: number;
  avgLatencyMs: number;
  errorRate: number;
  errorCount: number;
  successCount: number;
}

/**
 * Latency percentile result for a single API.
 */
export interface LatencyPercentiles {
  apiId: string;
  p50: number;
  p95: number;
  p99: number;
  sampleSize: number;
}

/**
 * Alert generated by the observability system.
 */
export interface QuotaAlert {
  userId: string;
  apiId: string;
  callCount: number;
  quota: number;
  usagePercent: number;
  type: 'QUOTA_WARNING';
}

/**
 * Trace detail for distributed tracing.
 */
export interface TraceDetail {
  traceId: string;
  apiId: string;
  endpoint: string;
  method: string;
  requestBody: unknown;
  responseBody: unknown;
  responseStatus: number;
  latencyMs: number;
  userId: string | null;
  isDemo: boolean;
  createdAt: Date;
}

/**
 * ObservabilityService — Real-time metrics, percentile calculation,
 * quota alerts, distributed tracing, and CSV export.
 *
 * Requirements: 10.1, 10.2, 10.3, 10.4, 10.5
 */
@Injectable()
export class ObservabilityService {
  private readonly logger = new Logger(ObservabilityService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Get real-time metrics for all APIs: call count, avg latency, error rate.
   *
   * Requirement 10.1: Show real-time metrics including call count, latency, and error rate per API.
   */
  async getMetrics(): Promise<ApiMetrics[]> {
    const apis = await this.prisma.api.findMany({
      select: { id: true, name: true },
    });

    const metrics: ApiMetrics[] = [];

    for (const api of apis) {
      const sessions = await this.prisma.sandboxSession.findMany({
        where: { apiId: api.id },
        select: { latencyMs: true, responseStatus: true },
      });

      const callCount = sessions.length;
      const errorCount = sessions.filter(
        (s) => s.responseStatus >= 400,
      ).length;
      const successCount = callCount - errorCount;
      const avgLatencyMs =
        callCount > 0
          ? sessions.reduce((sum, s) => sum + s.latencyMs, 0) / callCount
          : 0;
      const errorRate = callCount > 0 ? errorCount / callCount : 0;

      metrics.push({
        apiId: api.id,
        apiName: api.name,
        callCount,
        avgLatencyMs: Math.round(avgLatencyMs * 100) / 100,
        errorRate: Math.round(errorRate * 10000) / 10000,
        errorCount,
        successCount,
      });
    }

    return metrics;
  }

  /**
   * Get real-time metrics for a specific API.
   *
   * Requirement 10.1: Metrics per API.
   */
  async getMetricsByApi(apiId: string): Promise<ApiMetrics> {
    const api = await this.prisma.api.findUnique({
      where: { id: apiId },
      select: { id: true, name: true },
    });

    const apiName = api?.name ?? 'Unknown';

    const sessions = await this.prisma.sandboxSession.findMany({
      where: { apiId },
      select: { latencyMs: true, responseStatus: true },
    });

    const callCount = sessions.length;
    const errorCount = sessions.filter(
      (s) => s.responseStatus >= 400,
    ).length;
    const successCount = callCount - errorCount;
    const avgLatencyMs =
      callCount > 0
        ? sessions.reduce((sum, s) => sum + s.latencyMs, 0) / callCount
        : 0;
    const errorRate = callCount > 0 ? errorCount / callCount : 0;

    return {
      apiId,
      apiName,
      callCount,
      avgLatencyMs: Math.round(avgLatencyMs * 100) / 100,
      errorRate: Math.round(errorRate * 10000) / 10000,
      errorCount,
      successCount,
    };
  }

  /**
   * Calculate latency percentiles (p50, p95, p99) for a specific API.
   *
   * Uses the nearest-rank method:
   *   index = ceil(percentile / 100 * N) - 1
   *
   * Requirement 10.2: Show percentiles p50, p95, p99 per API.
   */
  async getLatencyPercentiles(apiId: string): Promise<LatencyPercentiles> {
    const sessions = await this.prisma.sandboxSession.findMany({
      where: { apiId },
      select: { latencyMs: true },
      orderBy: { latencyMs: 'asc' },
    });

    const latencies = sessions.map((s) => s.latencyMs);

    return {
      apiId,
      ...ObservabilityService.calculatePercentiles(latencies),
      sampleSize: latencies.length,
    };
  }

  /**
   * Pure static method to calculate percentiles from a sorted or unsorted array.
   * Uses the nearest-rank method:
   *   index = ceil(percentile / 100 * N) - 1
   *
   * Returns { p50: 0, p95: 0, p99: 0 } for empty arrays.
   */
  static calculatePercentiles(latencies: number[]): {
    p50: number;
    p95: number;
    p99: number;
  } {
    if (latencies.length === 0) {
      return { p50: 0, p95: 0, p99: 0 };
    }

    const sorted = [...latencies].sort((a, b) => a - b);
    const n = sorted.length;

    const percentile = (p: number): number => {
      const rank = Math.ceil((p / 100) * n) - 1;
      const index = Math.max(0, Math.min(rank, n - 1));
      return sorted[index];
    };

    return {
      p50: percentile(50),
      p95: percentile(95),
      p99: percentile(99),
    };
  }

  /**
   * Check all partners' consumption against their quotas and generate
   * QUOTA_WARNING alerts for those at or above 80%.
   *
   * Requirement 10.3: Alert when partner reaches 80% of quota.
   */
  async checkQuotaAlerts(): Promise<QuotaAlert[]> {
    const consumptions = await this.prisma.apiConsumption.findMany({
      where: { quota: { gt: 0 } },
    });

    const alerts: QuotaAlert[] = [];

    for (const consumption of consumptions) {
      const alert = ObservabilityService.evaluateQuotaAlert(
        consumption.userId,
        consumption.apiId,
        consumption.callCount,
        consumption.quota,
      );
      if (alert) {
        alerts.push(alert);
      }
    }

    // Create QUOTA_WARNING notifications for each alert
    for (const alert of alerts) {
      await this.prisma.notification.create({
        data: {
          userId: alert.userId,
          type: 'QUOTA_WARNING',
          title: 'Alerta de cuota de consumo',
          message:
            `Ha alcanzado el ${Math.round(alert.usagePercent * 100)}% de su cuota asignada ` +
            `(${alert.callCount}/${alert.quota} llamadas).`,
          metadata: {
            apiId: alert.apiId,
            callCount: alert.callCount,
            quota: alert.quota,
            usagePercent: alert.usagePercent,
          },
        },
      });
    }

    this.logger.log(
      `[OBSERVABILITY] Quota check complete: ${alerts.length} alerts generated`,
    );

    return alerts;
  }

  /**
   * Pure static method to evaluate whether a single partner/API pair
   * should trigger a QUOTA_WARNING alert.
   *
   * Returns a QuotaAlert if callCount >= 0.8 * quota, null otherwise.
   */
  static evaluateQuotaAlert(
    userId: string,
    apiId: string,
    callCount: number,
    quota: number,
  ): QuotaAlert | null {
    if (quota <= 0) return null;

    const usagePercent = callCount / quota;

    if (usagePercent >= 0.8) {
      return {
        userId,
        apiId,
        callCount,
        quota,
        usagePercent,
        type: 'QUOTA_WARNING',
      };
    }

    return null;
  }

  /**
   * Get trace detail by trace ID for distributed tracing.
   *
   * Requirement 10.4: Follow request end-to-end via trace ID.
   */
  async getTraceByTraceId(traceId: string): Promise<TraceDetail | null> {
    const session = await this.prisma.sandboxSession.findUnique({
      where: { traceId },
    });

    if (!session) return null;

    return {
      traceId: session.traceId,
      apiId: session.apiId,
      endpoint: session.endpoint,
      method: session.method,
      requestBody: session.requestBody,
      responseBody: session.responseBody,
      responseStatus: session.responseStatus,
      latencyMs: session.latencyMs,
      userId: session.userId,
      isDemo: session.isDemo,
      createdAt: session.createdAt,
    };
  }

  /**
   * Export consumption data per partner as CSV string.
   *
   * Requirement 10.5: Generate CSV with consumption data per partner.
   */
  async exportConsumptionCsv(): Promise<string> {
    const consumptions = await this.prisma.apiConsumption.findMany({
      include: {
        user: { select: { email: true, name: true, company: true } },
        api: { select: { name: true, slug: true } },
      },
    });

    const header =
      'userId,userEmail,userName,userCompany,apiId,apiName,apiSlug,callCount,quota,usagePercent,period';
    const rows = consumptions.map((c) => {
      const usagePercent =
        c.quota > 0
          ? Math.round((c.callCount / c.quota) * 10000) / 100
          : 0;
      return [
        c.userId,
        c.user.email,
        ObservabilityService.escapeCsvField(c.user.name ?? ''),
        ObservabilityService.escapeCsvField(c.user.company ?? ''),
        c.apiId,
        ObservabilityService.escapeCsvField(c.api.name),
        c.api.slug,
        c.callCount,
        c.quota,
        usagePercent,
        c.period,
      ].join(',');
    });

    return [header, ...rows].join('\n');
  }

  /**
   * Escape a CSV field: wrap in quotes if it contains commas, quotes, or newlines.
   */
  static escapeCsvField(value: string): string {
    if (
      value.includes(',') ||
      value.includes('"') ||
      value.includes('\n')
    ) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
  }
}
